# Generated by Django 3.2.11 on 2022-01-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion', models.CharField(db_index=True, max_length=30)),
                ('role', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('story', models.TextField()),
            ],
        ),
    ]
